### ISSUE TITLE
BES Cache

### ISSUE THREAD

**Issue by ffang10** [OPENDAP/bes#39] opened 2017-03-09 14:12 UTC
Our 1.13.1 server in operation had the BES cache filled in the last couple days. Based on the bes.conf spec below I wonder if the server should have started purging cached files when it reached 500MB? The cache is a 100GB area.

BES.UncompressCache.dir=/tmpdata/bes
BES.UncompressCache.prefix=bes_cache
BES.UncompressCache.size=500
BES.Uncompress.Retry=2000
BES.Uncompress.NumTries=10

**Comment by ndp-opendap** [comment] 2017-04-03 23:26
Fan,

On my dev system I find that the cache purging works as expected. I well get it going on a CentOS-6 system but in the meantime I had a question:

When the BES cache filled up, what did you encounter? 
- Many files in /tmpdata/bes with the prefix _ bes_cache_?
- Where there other files in there? 

I am asking because the BES utilizes a number of different file system caches and their combined sizes may have been responsible for part or possibly all of the discrepancy that you observed.

**Comment by ffang10** [comment] 2017-04-04 12:56
Nathan, I am not sure I saw the _bes_cache_ files. As far as I remember there are filenames starting with 'nc' - not sure if they are decompressed data. My memory is a little fuzzy now as it was a while ago and we cleaned up /tmpdata/bes immediately, and it hasn't happened since. We occasionally have such heavy users who is capable of pushing our server to a limit. I'll keep an eye out for the type of files in /tmpdata/bes should it happen again.

If it works in your test server, that's great. BTW the server this happened was an older 1.10.1.

**Comment by ffang10** [comment] 2017-04-04 12:56
Sorry - 1.13.1, not 1.10.1.

**Comment by ndp-opendap** [comment] 2017-04-04 14:25
Fan,

My guess is that filenames starting with _nc_ are temporary files created by the fileout_netcdf handler The NetCDF-C library doesn't support writing NetCDF files as a stream and so we need a place to stage the response. The location the temp files is controlled by the parameter _FONc.Tempdir_ in the file _/etc/bes/modules/fonc.conf_ I don't believe that there is any size management built into that handler, although the way it handles file should mean that they never accumulate. The fact that they did so would indicate that the BES was crashing at a crucial moment. This may well have been a side effect of the "large response size timeout" issue that we have been addressing , and if so should be fixed on the master branch and thus in the next release.

N

**Comment by ffang10** [comment] 2017-04-04 14:40
Confirming that we have this line in fonc.conf:

FONc.Tempdir=/tmpdata/bes/

Not exactly sure this was caused by BES crashing as there was no report from our operations that Hyrax was down at the time when our system detected "Device 100% full". 

Can we make sure fonc can manage its cache (either support a size limit, or as you said no accumulation), or if not delegate the management to the BES?

**Comment by ndp-opendap** [comment] 2017-04-04 15:27
Fan,

I think the problem was that while constructing a FONc response the beslistener process encountered a timeout alarm (new feature/behavior) , and this signal, while correctly caught, still left the temporary NetCDF file hanging around. So what I meant was not that the whole BES service was crashing, but one of the active beslistener processes encountering a timeout. When operating correctly the fileout_nectdf code creates files and then quickly “unlinks” them so that the only access to the file is via the open file descriptor held by the beslistener. Once it’s unlinked the file should not appear in an “ls -a” of the directory.

**Comment by ffang10** [comment] 2017-04-04 15:34
Thanks for the explanation. The timeout issue is one of the priority issues we are having with 1.13 servers; it is more critical than this one.

**Comment by ndp-opendap** [comment] 2017-04-04 15:42
Fan,

You have used the workaround in the /etc/olfs/olfs.xml 

            <timeOut>0</timeOut>

??

**Comment by ffang10** [comment] 2017-04-04 15:45
Yes for all our 1.13.1 servers in operations. So far so good.

However I did notice once or twice in 1.13.3 that BES still crashes with a zero timeout setting. I wasn't sure if it was the same issue.

**Comment by ndp-opendap** [comment] 2017-04-05 17:34
Fan,

I would be hard to say f they are related with more information. My thinking is that I will close this ticket  because:
- Cannot replicate
- I believe it to be a symptom of the (fixed) timeout problem. 

If it happens again please report it and I'll look at it again. Does that sound good?

Thanks,

Nathan

**Comment by ffang10** [comment] 2017-04-05 17:42
That sounds good. If it happens again I'll let you know.

**Comment by ndp-opendap** [comment] 2017-04-06 21:51
Closing!

**Comment by MattF-NSIDC** [comment] 2017-11-28 00:33
@ndp-opendap I hope you don't mind me resurrecting this issue, but I experienced this problem with Hyrax 1.13.4 (BES 3.18.0-1). I can consistently reproduce the problem and fill up our disk by crafting queries with large results. I think I've worked around the issue by setting the timeout in olfs.xml.

Based on, "I believe it to be a symptom of the (fixed) timeout problem": What version of BES contains the fix? We'd like to place a comment in our code to remind us to remove the workaround when we upgrade to that version.

Thanks for your time!

**Comment by ndp-opendap** [comment] 2017-11-28 00:55
Matt,
It's entirely possible that the "fix" wasn't so much so. I think all of the timeout mess was surely sorted in 3.18.0 (@jgallagher?) So I think we'll have to look at this again. Can you please reiterate what you are doing to invoke the issue?

Thanks,

Nathan

**Comment by MattF-NSIDC** [comment] 2017-11-29 00:23
Hi Nathan, thanks for getting back to me so promptly. I'm working on creating a repo that can be used to reproduce this issue on a VM. I'm not sure if resources matter for this question, but the VM I'm testing on has 2GB RAM.

Here is a request that I am able to use to create a 1.8GB file in `/tmp` that doesn't get cleaned up, aggregating over SPL4SMGP.003 data:

```http://example.com/opendap/aggregates/SPL4SMGP.003/h00v00.ncml.nc?Geophysical_Data_baseflow_flux[0:1:0][0:1:7][0:1:1623][0:1:3855],Geophysical_Data_heat_flux_ground[0:1:0][0:1:7][0:1:1623][0:1:3855],Geophysical_Data_heat_flux_latent[0:1:0][0:1:7][0:1:1623][0:1:3855],Geophysical_Data_heat_flux_sensible[0:1:0][0:1:7][0:1:1623][0:1:3855],Geophysical_Data_height_lowatmmodlay[0:1:0][0:1:7][0:1:1623][0:1:3855],Geophysical_Data_land_evapotranspiration_flux[0:1:0][0:1:7][0:1:1623][0:1:3855],Geophysical_Data_land_fraction_saturated[0:1:0][0:1:7][0:1:1623][0:1:3855],Geophysical_Data_land_fraction_snow_covered[0:1:0][0:1:7][0:1:1623][0:1:3855],Geophysical_Data_land_fraction_unsaturated[0:1:0][0:1:7][0:1:1623][0:1:3855]```

Note that the netcdf output file size is just short of our total RAM. If I add one more variable to the request, we get this error in the browser but no errors in bes.log:

```
Bad Gateway!

The proxy server received an invalid response from an upstream server.

The proxy server could not handle the request GET /opendap/aggregates/SPL4SMGP.003/h00v00.ncml.nc.

Reason: Error reading from remote server
```

The host in question is not available from outside our network, but maybe I'll put up a droplet to demonstrate this issue. What's the best way to contact you with a test URL?

**Comment by MattF-NSIDC** [comment] 2017-12-01 01:38
@ndp-opendap Do you have a way for me to contact you to provide a login to a server reproducing the issue? For now, I can give you a repository that _should_ allow you to reproduce the issue on your end. Just follow the README instructions to reproduce the issue.

https://bitbucket.org/MattF-NSIDC/opendap-tmp-overflow-sscce

**Comment by ndp-opendap** [comment] 2017-12-01 14:22
At OPeNDAP we are encrypted email friendly!
You can get my public gpg/pgp key from our website: https://www.opendap.org/about/engineering
Send me your public key and we should be good to go.

Nathan

**Comment by ndp-opendap** [comment] 2017-12-04 23:07
Hi Matt,

I m having some issues trying to get the container you sent running, but after hacking every mount point I got it started. I was unable to use your getdata.sh script until I discovered that I had to actually use a browser to go to: https://n5eil01u.ecs.nsidc.org/SMAP/SPL4SMGP.003/2015.03.31/ where I got redirected to EDL (expected) but I had to accept the NSIDC EULA before it let me through. Once I did that the command line started to work. I got lucky there - you might want to keep that little bootstrap gem in mind for the future.

The data is downloading now, I'll keep you posted.

N

**Comment by MattF-NSIDC** [comment] 2017-12-05 17:28
> was unable to use your getdata.sh script until I discovered that I had to actually use a browser to go to: https://n5eil01u.ecs.nsidc.org/SMAP/SPL4SMGP.003/2015.03.31/ where I got redirected to EDL (expected) but I had to accept the NSIDC EULA before it let me through

Oh, wow. I think you only have to accept the EULA once for your account, then the script should work. I completely forgot I had to do that way back when. Sorry about that! 

I really want to get this reproduced for you ASAP, but I think I'll be a bit busy to finish putting together the VM until Thursday. It was taking more time than I had available.

**Comment by ndp-opendap** [comment] 2017-12-06 17:07
Hi Matt,

I spun up an AWS CentOS-7 system in a t2.small (2GB of RAM) ad I have Hyrax installed and running:

http://34.229.209.112:8080/opendap/

I'll get you data loaded in there but to be

**Comment by ndp-opendap** [comment] 2017-12-07 00:01
Hi Matt,

I fired up an AWS system running CentOS-7 and pulled you examples and Hyrax onto it: With everything in place I can reliably replicate the problem doing just this much:
```shell
#!/bin/bash
test_url="http://127.0.0.1:8080/opendap/aggregates/h00v00.ncml.nc?Geophysical_Data_baseflow_flux[0:1:0][0:1:7][0:1:1623][0:1:3855],Geop
hysical_Data_heat_flux_ground[0:1:0][0:1:7][0:1:1623][0:1:3855],Geophysical_Data_heat_flux_latent[0:1:0][0:1:7][0:1:1623][0:1:3855],Geo
physical_Data_heat_flux_sensible[0:1:0][0:1:7][0:1:1623][0:1:3855],Geophysical_Data_height_lowatmmodlay[0:1:0][0:1:7][0:1:1623][0:1:385
5],Geophysical_Data_land_evapotranspiration_flux[0:1:0][0:1:7][0:1:1623][0:1:3855],Geophysical_Data_land_fraction_saturated[0:1:0][0:1:
7][0:1:1623][0:1:3855],Geophysical_Data_land_fraction_snow_covered[0:1:0][0:1:7][0:1:1623][0:1:3855],Geophysical_Data_land_fraction_uns
aturated[0:1:0][0:1:7][0:1:1623][0:1:3855]"
curl --globoff "${test_url}" > bad_h00v00.ncml.nc  2>&1 &
PID=$!
echo "Requesting ridiculously large amount of data (PID $PID)..."
```
And then issuing `kill $PID` myself from the command line.

I think this not a re manifestation of Hyrax-39 so I am going to make a new Ticket in our JIRA - I'll send you a link - and start trying to see where this goes awry.

Thanks for your patience,

N

**Comment by MattF-NSIDC** [comment] 2017-12-07 00:02
Nathan,

That's fantastic news. Very glad you were able to reproduce this. Thanks so much for taking the time to dig in to this. Please let me know what else I can do to help!

**Comment by ndp-opendap** [comment] 2017-12-07 00:39
I am shifting this to a new ticket in JIRA: https://opendap.atlassian.net/browse/HYRAX-561

**Closed by ndp-opendap** 2017-12-07 00:39 UTC
Labels: NASA
